defaults:
  - scope:
      path: "" # Kök klasör
      type: "pages"
    values:
      permalink: /:path/tr
  - scope:
      path: "tr.html" # tr.html dosyası için kapsam
      type: "pages"
    values:
      permalink: /:path
