defaults:
  - scope:
      path: "" # Kök klasör
      type: "pages"
    values:
      permalink: /:path
  - scope:
      path: "tr" # tr klasörü için kapsam
      type: "pages"
    values:
      permalink: /tr.html
